swagger: "2.0"
info:
  title: Argent Bank Transactions API documentation
  description: Contains all transactions API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user-accounts/allAccounts:
    post:
      security:
        - Bearer: []
      tags:
        - User's accounts
      summary: Transactions API
      description: API for fetching all user's accounts
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: User's Accounts retrieved successfully
          schema:
            $ref: "#/definitions/AccountOverview"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user-accounts/{accountId}/{month}:
    post:
      security:
        - Bearer: []
      tags:
        - User's account transactions
      summary: Transactions API
      description: API for fetching all transactions of a user's account for a specific month
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: accountId
          description: Account ID
          required: true
          type: string
        - in: path
          name: month
          description: Month
          required: true
          type: number
      produces:
        - application/json
      responses:
        "200":
          description: User's Account transactions retrieved successfully
          schema:
            $ref: "#/definitions/AccountTransactions"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user-accounts/{transactionId}:
    post:
      security:
        - Bearer: []
      tags:
        - Transaction's details
      summary: Transactions API
      description: API for getting more details of a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: transactionId
          description: Transaction ID
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Transaction retrieved successfully
          schema:
            $ref: "#/definitions/Transaction"
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transactions updates
      summary: Transactions API
      description: API for updating a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: transactionId
          description: Transaction ID
          required: true
          type: string
        - in: body
          name: body
          description: Update a transaction
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction updated successfully
          schema:
            $ref: "#/definitions/Transaction"
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transactions updates
      summary: Transactions API
      description: API for updating a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: transactionId
          description: Transaction ID
          required: true
          type: string
      produces:
        - application/json
      responses:
        "204":
          description: Transaction deleted successfully
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  AccountOverview:
    type: object
    properties:
      accountId:
        type: string
        description: account id
      accountName:
        type: string
        description: account name
      balance:
        type: number
        description: account balance
      currency:
        type: string
        description: account currency
  AccountTransactions:
    type: object
    properties:
      accountId:
        type: string
        description: account id
      accountName:
        type: string
        description: account name
      month:
        type: string
        description: month
      transactions:
        type: array
        items:
          $ref: "#/definitions/Transaction"
  Transaction:
    type: object
    properties:
      transactionId:
        type: string
        description: transaction id
      date:
        type: date
        description: transaction date
      description:
        type: string
        description: transaction description
      amount:
        type: number
        description: transaction amount
      balance:
        type: number
        description: transaction balance
      type:
        type: string
        description: transaction type
      category:
        type: string
        description: transaction category
      notes:
        type: string
        description: transaction notes
